parameters:
#    tlt_ticket.example.class: Tlt\TicketBundle\Example

services:
#    tlt_ticket.example:
#        class: %tlt_ticket.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]